apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "tutorial"
  annotations:
    sonarqube.org/project-key: [NikaPozar_tutorial]
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
