apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "tutorial"
  annotations:
    sonarsource.com/project-key: tutorial/NikaPozar_tutorial
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
